FROM node:alpine3.18

# Declare build-time variables
ARG MONGO_URI
ARG PORT
ARG SECRET_TOKEN
ARG ADMIN_EMAIL
ARG NODEMAILER_EMAIL
ARG NODEMAILER_PASSWORD
ARG SECRET_STRIPE_KEY
ARG STRIPE_ANNUAL_SUBSCRIPTION
ARG STRIPE_MONTHLY_SUBSCRIPTION
ARG CLIENT_URL
ARG APP_RESET_PASSWORD_URL
ARG ENDPOINT_SECRET
ARG CLIENT_URL_SUCCESS
ARG CLIENT_URL_CANCEL

# Set environment variables  
ENV MONGO_URI=$MONGO_URI
ENV PORT=$PORT
ENV SECRET_TOKEN=$SECRET_TOKEN
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ENV NODEMAILER_EMAIL=$NODEMAILER_EMAIL
ENV NODEMAILER_PASSWORD=$NODEMAILER_PASSWORD
ENV SECRET_STRIPE_KEY=$SECRET_STRIPE_KEY
ENV STRIPE_ANNUAL_SUBSCRIPTION=$STRIPE_ANNUAL_SUBSCRIPTION
ENV STRIPE_MONTHLY_SUBSCRIPTION=$STRIPE_MONTHLY_SUBSCRIPTION
ENV CLIENT_URL=$CLIENT_URL
ENV APP_RESET_PASSWORD_URL=$APP_RESET_PASSWORD_URL
ENV ENDPOINT_SECRET=$ENDPOINT_SECRET
ENV CLIENT_URL_SUCCESS=$CLIENT_URL_SUCCESS
ENV CLIENT_URL_CANCEL=$CLIENT_URL_CANCEL


# Debug: Print environment variables to verify they are set correctly
RUN echo "MONGO_URI=${MONGO_URI}" \
    && echo "PORT=${PORT}" \
    && echo "SECRET_TOKEN=${SECRET_TOKEN}" \
    && echo "ADMIN_EMAIL=${ADMIN_EMAIL}" \
    && echo "NODEMAILER_EMAIL=${NODEMAILER_EMAIL}" \
    && echo "NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}" \
    && echo "SECRET_STRIPE_KEY=${SECRET_STRIPE_KEY}" \
    && echo "STRIPE_ANNUAL_SUBSCRIPTION=${STRIPE_ANNUAL_SUBSCRIPTION}" \
    && echo "STRIPE_MONTHLY_SUBSCRIPTION=${STRIPE_MONTHLY_SUBSCRIPTION}" \
    && echo "CLIENT_URL=${CLIENT_URL}" \
    && echo "APP_RESET_PASSWORD_URL=${APP_RESET_PASSWORD_URL}"

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the application
CMD ["npm", "run", "dev"]
